### ISSUE TITLE
Can`t create events in calendar

### ISSUE THREAD

**Issue by PetroGolovnya** [modoboa/modoboa-radicale#52]
Modoboa: 1.15
 installer used: Yes
 Webserver: Nginx
 OS: Ubuntu 20.04 LTS

Radicale 2.1.11 from ubuntu repo, modoba install installed 3.x

Steps to reproduce

With a fresh installation done trough the installer, try to create a new event in calendar Calendar1 for a user and error 500.

ls /srv/radicale/collections/collection-root/mrfadi@air6x.com/
Calendar1  contacts  Meetings

Server response with error - [https://paste.centos.org/view/d5deae8f](https://paste.centos.org/view/d5deae8f)
Radicale config - [http://dpaste.com//1KDGW78](http://dpaste.com//1KDGW78)

**Comment by tonioo** [comment]
@PetroGolovnya The first link has expired...

**Comment by PetroGolovnya** [comment]
[http://paste.org.ru/?f6h6qh](http://paste.org.ru/?f6h6qh)

**Comment by tonioo** [comment]
@PetroGolovnya I see you're using python 3.8. Modoboa has not been officialy tested with this version.

**Comment by PetroGolovnya** [comment]
Which version  of python you recomend?

**Comment by tonioo** [comment]
Python 3.7 is the most recent version which is known as compatible.

**Comment by PetroGolovnya** [comment]
ОК. I try swith to 3.7 and make calendar test.

**Comment by PetroGolovnya** [comment]
Modoboa: 1.15
installer used: Yes
Webserver: Nginx
OS:  Ubuntu 18.04

Radicale 2.1.12 in /srv/radicale
Python 3.6.9

just add calendar and refresh [http://paste.org.ru/?egabfz](http://paste.org.ru/?egabfz)
When i try to add event in calendar [http://paste.org.ru/?b59r4d](http://paste.org.ru/?b59r4d)
Radicale config [http://paste.ubuntu.com/p/rgpgRyHbQC/](http://paste.ubuntu.com/p/rgpgRyHbQC/)

**Comment by tonioo** [comment]
@PetroGolovnya does you event contains any special characters? Have you tried using only ASCII chars?

**Comment by PetroGolovnya** [comment]
Links in last message still accessible.
Event not contains any special charters, cyrillic \ chinese lettrs.
For example:
![изображение](https://user-images.githubusercontent.com/25701171/85497377-02ba9f80-b608-11ea-9571-9b5f8f9b260b.png)

**Comment by tonioo** [comment]
@PetroGolovnya Sorry for the delay but can you check that you have caldav version 0.6.2 installed in your virtualenv?

**Comment by vnen** [comment]
I have the same issue, also using Python 3.8.

Not sure if I'm looking at the right place but it looks like caldav version is 0.5.0 here. Is there an easy way to update this (I'm not familiar with Python virtualenv)?

**Comment by tonioo** [comment]
@vnen Is this issue still happening?

**Comment by vnen** [comment]
@tonioo yes. I've upgraded Modoboa to 1.17.0 but I still get the same error.

**Comment by tonioo** [comment]
@vnen Looks like there was a permission issue in the default configuration. I've pushed a fix and I'll release a new version of the plugin soon. Don't forget to update your plugins too.

**Comment by vnen** [comment]
@tonioo I updated it but it seems the rights file isn't regenerated, so it's still an issue. Is there a way to force it to regenerate? Or should I just do it by hand?

**Comment by tonioo** [comment]
@vnen You can call the same command using the --force option. (Look at the /etc/cron.d/modoboa file)
